### ISSUE TITLE
Ad lol

### ISSUE THREAD

**Issue by snakysnake** [Ushie/ushie.dev#1]
Hey i saw you were interested in generating invoices using javascript!
Maybe check out my repo called "invoice-js" to generate your invoices using js!
its really open source and not just a wrapper for an api, runs well in node and in the browser

**Comment by Ushie** [comment]
Hi,

Thanks for the recommendation, I've checked out your repository (and may open issues later) and will consider it if I ever revisit the repository in question

That aside, I recommend that you use the contact email on people's profiles over opening issues in unrelated repositories, an unfortunate thing with GitHub is the lack of private messages
